### PR TITLE
fix(server): obtain garage configuration dynamically

### LINKED ISSUE #11: garages and npwd are not connected
### Summary

like there was a change that resulted in this not being connected

### Reproduction

image
after using the latest qbx_garages version npwd_qbx_garages an error appears like this and when in ingame an error in the npwd file on line 34 error global config

### Expected behavior

..

### Actual behavior

.

### Additional context

.

### Current Version

...

### Custom Resources

npwd_qbx_garages

### PR DESCRIPTION
**Pull request by solareon**
## Description

Fixes obtaining garage config from `qbx_garages`. Adds event handlers for `qbx_garages` restarts and for garages being registered

Blocked on https://github.com/Qbox-project/qbx_garages/pull/109

Fixes #11 

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Comment by solareon** [comment]
Tested per [here](https://discord.com/channels/1012753553418354748/1031968831595352085/1257678045352034375)

**Comment by kaptenbintang** [comment]
to fix error when opening garage app from phone change

from:
`vehicleData.garage = garageConfig.garages[vehicleData.garage]?.label or locale('states.garage_unknown')`

into:
`vehicleData.garage = garageConfig[vehicleData.garage]?.label or locale('states.garage_unknown')`

image

**Comment by solareon** [comment]
> to fix error when opening garage app from phone change into this
> 
> `vehicleData.garage = garageConfig[vehicleData.garage]?.label or locale('states.garage_unknown')`
> 
> image

I incorporated this fix already in [`ddd491f` (#12)](https://github.com/Qbox-project/npwd_qbx_garages/pull/12/commits/ddd491f51a9934e020caffe2301a1f2e38d264c9). Thank you for your help in testing the fixes.

File: server/server.lua [hunk 1]
```diff
@@ -31,8 +32,18 @@ lib.callback.register('npwd_qbx_garages:server:getPlayerVehicles', function(sour
...
+		vehicleData.garage = garageConfig[vehicleData.garage]?.label or locale('states.garage_unknown')
 	end
 
 	return result
+end)
+
+AddEventHandler('onResourceStart', function(resourceName)
+    if resourceName == 'qbx_garages' then
+        garageConfig = exports.qbx_garages:GetGarages()
+    end
```
Comment (Manason) [inline server/server.lua:44]: This seems redundant as we are calling this same export at top of file

**Review by Manason — CHANGES_REQUESTED** [review]

File: server/server.lua (hunk 1 above)
Comment (solareon) [reply server/server.lua:44]: This is to catch restarts of qbx_garages without kicking this resource

**Review by Manason — APPROVED** [review]
